// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsyLjAbIQXkhVVVXbq1QhGsCxGbMrijow',
    appId: '1:699384102140:android:270e210bd867b291d6eb79',
    messagingSenderId: '699384102140',
    projectId: 'flutter-projects-f3ceb',
    storageBucket: 'flutter-projects-f3ceb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEintMjBKGnDUrh9337EijkOuUmxEpCx4',
    appId: '1:699384102140:ios:50b5ddcbafcd4c3ed6eb79',
    messagingSenderId: '699384102140',
    projectId: 'flutter-projects-f3ceb',
    storageBucket: 'flutter-projects-f3ceb.appspot.com',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEintMjBKGnDUrh9337EijkOuUmxEpCx4',
    appId: '1:699384102140:ios:a58723eb66af933bd6eb79',
    messagingSenderId: '699384102140',
    projectId: 'flutter-projects-f3ceb',
    storageBucket: 'flutter-projects-f3ceb.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

}